### ISSUE TITLE
Support objects

### ISSUE THREAD

**Issue by brandonpittman** [joe-bell/cx#8]
**Describe the solution you'd like**
I'd love to use cx in place of clsx but I need objects to be accepted (along with arrays).

```js
setClasses(cx({"text-red-600": isInvalid}))
```

Are you interested in having this in cx?

**Comment by joe-bell** [comment]
You can achieve similar behaviour at the moment with the current API:

```jsx
className={cx(
  isInvalid && "text-red-600",
)}
```

So to be totally honest, this isn't something I'm willing to invest time implementing. Thanks for taking the time to write up this suggestion though 🙏🏼

**Comment by brandonpittman** [comment]
@joe-bell Okay, back to clsx then.

**Comment by brandonpittman** [comment]
```typescript
{
	"bg-red-600 text-white": errors.length > 1,
	"bg-white text-blue-600: errors.length <= 1,
	"hover:bg-purple-600 hover:shadow-sm": shouldApplyHoverStyling
}
```

This kind of stuff can get complicated and `&&`-ing everything is harder to read. Maybe it's just me. Sorry for troubling you.

**Comment by joe-bell** [comment]
Alternatively, you could try this in the meantime?

```js
cx(
  ...(errors.length > 1 && [
    "bg-red-600",
    "text-white"
  ]),
  ...(errors.length <= && [
    "bg-white",
    "text-blue-600"
  ]),
  ...(shouldApplyHoverStyling && [
    "bg-purple-600",
    "hover:shadow-sm"
  ])
)
```
